### ISSUE TITLE
Compilation failing during installation

### ISSUE THREAD

**Issue by cassidyrobinhold** [oyvble/MPSproto#1]
Hello! I am trying to download from GitHub on my MacOS:
```
library(devtools)
install_github("oyvble/MPSproto")
```
But I am having an issue with compilation where my "omp.h" file cannot be found. I've tried a few routes for troubleshooting with no luck. I'm a bit unfamiliar with C++. Any suggestions on moving forward with installation?

Here is the error I'm getting:

```
Downloading GitHub repo oyvble/MPSproto@HEAD
── R CMD build ──────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/8_/vyktsh3d13g2x458jzq_2cb11bgtbb/T/RtmpUbzdPW/remotesee8898354c4/oyvble-MPSproto-80238af/DESCRIPTION’ ...
─  preparing ‘MPSproto’:
✔  checking DESCRIPTION meta-information
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘MPSproto_0.8.1.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning: invalid gid value replaced by that for user 'nobody'
   
* installing *source* package ‘MPSproto’ ...
** using staged installation
** libs
clang++ -mmacosx-version-min=10.13 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include    -fPIC  -Wall -g -O2  -c loglikPrediction_allcomb.cpp -o loglikPrediction_allcomb.o
loglikPrediction_allcomb.cpp:14:10: fatal error: 'omp.h' file not found
#include <omp.h> //parallelization
         ^~~~~~~
1 error generated.
make: *** [loglikPrediction_allcomb.o] Error 1
ERROR: compilation failed for package ‘MPSproto’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/MPSproto’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/8_/vyktsh3d13g2x458jzq_2cb11bgtbb/T//RtmpUbzdPW/fileee8833765e15/MPSproto_0.8.1.tar.gz’ had non-zero exit status
```

And here is my clang version:
```
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: x86_64-apple-darwin22.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Thank you!!

**Comment by oyvble** [comment]
Hi @cassidyrobinhold!
I think the reason for this is that "clang compiler" you use does not contain the "OpenMP" library (includes "omp.h").
To make this work you will need to install and re-direct the compiler to be "gcc".
See steps 4-6 in the "MAC version" manual from the EuroForMix website:
http://www.euroformix.com/sites/default/files/InstallationMAC.pdf

Best regards Øyvind

**Comment by cassidyrobinhold** [comment]
Øyvind,

Thank you so much for your response :)
The gcc install didn't work for me, but I did manage to get everything installed using a combination of your advice and the instructions provided here: https://mac.r-project.org/openmp/

I ended up downloading the libomp OpenMP tar ball that contained the omp files from the link above. Then added these flags to ~/.R/Makevars
```
CPPFLAGS += -Xclang -fopenmp
LDFLAGS += -lomp
```

Thanks!

**Comment by oyvble** [comment]
Hi @cassidyrobinhold, 
I am glad you managed to find a solution. 
This is very useful, thank you for sharing.
